liip_imagine:
    driver: gd
    resolvers:
        default:
            web_path:
                web_root: '%kernel.project_dir%/public'
                cache_prefix: media/cache
    filter_sets:
        reference_thumb:
            quality: 80
            filters:
                thumbnail:
                    size: [600, 400]
                    mode: outbound
