liip_imagine:
    driver: gd
    twig:
        mode: lazy
    resolvers:
        default:
            web_path:
                web_root: '%kernel.project_dir%/public'
                cache_prefix: media/cache
    filter_sets:
        reference_landscape:
            quality: 85
            filters:
                thumbnail:
                    size: [1080, 864]
                    mode: outbound
        reference_portrait:
            quality: 85
            filters:
                thumbnail:
                    size: [1080, 1350]
                    mode: outbound
