version: "3.9"

services:
    database:
        image: mysql:8
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            - MYSQL_DATABASE=${NAME}
            - MYSQL_USER=${NAME}
            - MYSQL_PASSWORD=${NAME}
            - MYSQL_ROOT_PASSWORD=${NAME}

    php:
        build: ../../components/docker/php
        restart: unless-stopped
        working_dir: /app
        userns_mode: host
        environment:
            - HOME=/tmp
            - TRUSTED_PROXIES=127.0.0.1
            - TEST_ENVIRONMENT=1
        depends_on:
            - database
        volumes:
            - ../../components/app:/app:cached
            - ../../artifacts:/artifacts:delegated
        tmpfs:
            - /tmp

    nginx:
        build: ../../components/docker/nginx
        working_dir: /app
        restart: unless-stopped
        userns_mode: host
        ports:
            - "${API_PORT}:80"
        volumes:
            - ../../components/app/public:/app/public:ro
        depends_on:
            - php
